### ISSUE TITLE
Question about datasets

### ISSUE THREAD

**Issue by ymhzyj** [IDLabMedia/comprint#4]
Hi, your work is really fascinating to me .  I have not obtained the VIPP dataset through searching and contacting the original author, and would like to ask you how to obtain it. Can you offer me some help about the access to the VIPP. Thanks a lot !

**Comment by hmareen** [comment]
Hi,

The VIPP dataset can be downloaded from their website: [http://clem.dii.unisi.it/~vipp/datasets.html](http://clem.dii.unisi.it/~vipp/datasets.html)
It is the one called "A Framework for Decision Fusion in Image Forensics based on Dempster-Shafer Theory of Evidence."

Kind regards,
Hannes
